### ISSUE TITLE
shadowed HikariCP package on HuskbungeeRTP

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskBungeeRTP#6]
See ticket-0259

**Comment by Iotados** [comment]
> [21:51:01] [Server thread/INFO]: [HuskBungeeRTP] Enabling HuskBungeeRTP v1.1
[21:51:01] [Server thread/ERROR]: Error occurred while enabling HuskBungeeRTP v1.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'void com.zaxxer.hikari.HikariDataSource.setKeepaliveTime(long)'
    at me.william278.huskbungeertp.mysql.MySQL.load(MySQL.java:62) ~[?:?]
    at me.william278.huskbungeertp.mysql.DataHandler.loadDatabase(DataHandler.java:24) ~[?:?]
    at me.william278.huskbungeertp.HuskBungeeRTP.onEnable(HuskBungeeRTP.java:133) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-788]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-788]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-788]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-788]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-788]
    at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-788]
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-788]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-788]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
    at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by WiIIiam278** [comment]
Fixed in [2a7a9ab](https://github.com/WiIIiam278/HuskBungeeRTP/commit/2a7a9ab37feae81aa2b59ef7fec1260e7bfbd2c3)
