### ISSUE TITLE
MySQL syntax exception during startup

### ISSUE THREAD

**Issue by galexrt** [WiIIiam278/HuskBungeeRTP#7]
```
[12:25:35 INFO]: [HuskBungeeRTP] Enabling HuskBungeeRTP v1.1.1
[12:25:35 INFO]: [me.william278.huskbungeertp.libraries.hikaricp.hikari.HikariDataSource] HuskBungeeRTPHikariPool - Starting...
[12:25:36 INFO]: [me.william278.huskbungeertp.libraries.hikaricp.hikari.pool.HikariPool] HuskBungeeRTPHikariPool - Added connection com.mysql.cj.jdbc.ConnectionImpl@6ea6cb77
[12:25:36 INFO]: [me.william278.huskbungeertp.libraries.hikaricp.hikari.HikariDataSource] HuskBungeeRTPHikariPool - Start completed.
[12:25:36 ERROR]: [HuskBungeeRTP] An error occurred creating tables on the MySQL database:
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(CURRENT_TIMESTAMP),`dest_world` tinytext NOT NULL,`dest_x` double NOT NULL,`des' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at me.william278.huskbungeertp.libraries.hikaricp.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HuskBungeeRTP-1.1.1.jar:?]
	at me.william278.huskbungeertp.libraries.hikaricp.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HuskBungeeRTP-1.1.1.jar:?]
	at me.william278.huskbungeertp.mysql.MySQL.load(MySQL.java:74) ~[HuskBungeeRTP-1.1.1.jar:?]
	at me.william278.huskbungeertp.mysql.DataHandler.loadDatabase(DataHandler.java:24) ~[HuskBungeeRTP-1.1.1.jar:?]
	at me.william278.huskbungeertp.HuskBungeeRTP.onEnable(HuskBungeeRTP.java:133) ~[HuskBungeeRTP-1.1.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-78]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-78]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[paper-1.19.jar:git-Paper-78]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:420) ~[paper-1.19.jar:git-Paper-78]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-78]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-78]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-78]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

I get this error on Paper `git-Paper-78 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b327e17)` with a Percona MySQL server version `5.7.36-39-57-log Percona XtraDB Cluster` (should be similar to a "normal" MySQL 5.7.36 server).

Please let me know if you need more information to look into this issue. Thanks!

**Comment by WiIIiam278** [comment]
HuskBungeeRTP uses MySQL v8+ features which aren't supported in your database implementation :) Please update MySQL. Thank you.
